base_url = "https://ericscouten.travel"

title = "Eric Scouten :: Travel"
description = "In which I share notes from my travels."
default_language = "en"

theme = "zola-es-theme"

compile_sass = true
build_search_index = true

generate_feed = true
feed_filename = "rss.xml"

[markdown]
highlight_code = false
smart_punctuation = true

[extra]
mastodon_site_account = "@travel@ericscouten.social"
mastodon_site_url = "https://ericscouten.social/@travel"
credits = "by @scouten@techhub.social"
hashtags = "#travel #photography"
endmark = true
es_site = "travel"
map_clustering = false
is_dark = true

[[taxonomies]]
name = "country"

[[taxonomies]]
name = "state"

# I really wish taxonomies could have titles independent of their names!
[extra.taxonomies.country]
title = "Countries Iâ€™ve Visited"
sort = "date"

[extra.taxonomies.state]
title = "US States and Territories"
sort = "date"
